
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynemjstlldiipyqazedz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluZW1qc3RsbGRpaXB5cWF6ZWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDQyNzksImV4cCI6MjA2MTMyMDI3OX0.-_9sbizxAMenKy9oVLzP1s_Lh-svfxGaVe-zGNkHjDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: 'trustlens-auth',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'X-Client-Info': 'trustlens-web@1.0.0'
    }
  }
});

// Enhanced error handling and logging
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'SIGNED_IN') {
    console.log('✅ User authenticated successfully');
  } else if (event === 'SIGNED_OUT') {
    console.log('👋 User signed out');
  } else if (event === 'TOKEN_REFRESHED') {
    console.log('🔄 Auth token refreshed');
  }
});
