// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynemjstlldiipyqazedz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluZW1qc3RsbGRpaXB5cWF6ZWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDQyNzksImV4cCI6MjA2MTMyMDI3OX0.-_9sbizxAMenKy9oVLzP1s_Lh-svfxGaVe-zGNkHjDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});